### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by sdwood** [taeram/hearth#3]
got this error starting setup:
```$ http:///var/run/docker.sock/v1.17/build?dockerfile=Dockerfile&rm=1&t=sabnzbd: dial u nix /var/run/docker.sock: permission denied```

all I had to to do was add htpcd user to docker group

```$ sudo usermod -a -G docker htpcd```

started to run after that

**Comment by taeram** [comment]
Official solution here: https://docs.docker.com/installation/ubuntulinux/#optional-configurations-for-docker-on-ubuntu

Closing this issue as it's a Docker configuration issue, and doesn't actually have anything directly to do with Hearth.
